# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /mnt/mongodb
  wiredTiger:
    collectionConfig:
      blockCompressor: none
      configString: allocation_size=128k,internal_page_max=128k,leaf_page_max=128k

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1
  tls:
    mode: allowTLS # disabled, allowTLS, preferTLS, requireTLS
    certificateKeyFile: /etc/ssl/mongodb_certkey.pem
    CAFile: /etc/ssl/ca_certs.pem

# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

security:
  authorization: enabled
  javascriptEnabled: false

#operationProfiling:

#replication:

#sharding:

## Enterprise-Only Options:

#auditLog:

